apiVersion: v1
kind: Secret
metadata:
  name: {{ include "luna-backend.fullname" . }}-secrets
  labels:
    {{- include "luna-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "luna-backend.databaseURL" . | quote }}
  redis-url: {{ include "luna-backend.redisURL" . | quote }}
  rabbitmq-url: {{ include "luna-backend.rabbitmqURL" . | quote }}
  {{- if .Values.minio.external.enabled }}
  minio-access-key: {{ .Values.minio.external.accessKey | quote }}
  minio-secret-key: {{ .Values.minio.external.secretKey | quote }}
  {{- else }}
  minio-access-key: {{ .Values.minio.auth.rootUser | quote }}
  minio-secret-key: {{ .Values.minio.auth.rootPassword | quote }}
  {{- end }}
  jwt-secret-key: {{ .Values.app.env.JWT_SECRET_KEY | quote }}
